import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:phosphor_flutter/phosphor_flutter.dart';
import 'firebase_options.dart';

import 'core/network/api_client.dart';
import 'core/offline/offline_queue.dart';
import 'core/services/push_notification_service.dart';
// P0-VE-001 PLATINUM: Deep link handler for email verification & password reset
import 'core/services/deep_link_service.dart';
// GAP-M1 PLATINUM: Firebase Crashlytics — production crash reporting
import 'core/services/crashlytics_service.dart';
// GAP-M2 PLATINUM: Firebase Performance — app performance monitoring
import 'core/services/performance_service.dart';
import 'core/theme/app_theme.dart';
import 'core/theme/theme_cubit.dart';
import 'core/i18n/locale_cubit.dart';
import 'core/widgets/connectivity_banner.dart';
import 'features/auth/bloc/auth_bloc.dart';
import 'features/auth/repositories/auth_repository.dart';
import 'features/auth/screens/login_screen.dart';
import 'features/dashboard/screens/dashboard_screen.dart';
import 'features/notifications/bloc/notifications_bloc.dart';
import 'features/notifications/bloc/notifications_event.dart';
import 'features/notifications/models/notification_model.dart';
import 'features/onboarding/screens/onboarding_screen.dart';
import 'features/onboarding/screens/splash_screen.dart';
import 'features/search/data/search_repository.dart';
import 'features/search/bloc/search_bloc.dart';
// P0-002 REMEDIATION: Deep link target screens
import 'features/escrow/screens/escrow_summary_screen.dart';
import 'features/project/screens/project_details_screen.dart';
import 'features/admin/screens/admin_kyc_screen.dart';
import 'features/admin/screens/admin_escrow_screen.dart';
import 'features/wallet/screens/wallet_screen.dart';
import 'features/impact/screens/impact_inbox_screen.dart';

/// Global navigator key — allows OfflineQueue to show SnackBars from
/// outside the widget tree (e.g., from background connectivity callbacks).
final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // UXA-006 FIX: Limit ImageCache to prevent OOM on Infinite Scroll
  // Default is 1000 images or 100MB, which crashes low-end Syrian phones
  PaintingBinding.instance.imageCache.maximumSize = 100;
  PaintingBinding.instance.imageCache.maximumSizeBytes = 50 * 1024 * 1024; // 50 MB

  // Initialize Firebase with platform-specific options (generated by FlutterFire CLI)
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Initialize production API client
  await NammerhaApiClient.instance.init();

  // GAP-M1 PLATINUM: Initialize Crashlytics EARLY — before any other code runs.
  // Wires FlutterError.onError + PlatformDispatcher.onError to capture ALL
  // uncaught exceptions in production. Disabled in debug mode.
  CrashlyticsService.instance.init();

  // GAP-M2 PLATINUM: Initialize Performance Monitoring.
  // Captures app startup time, HTTP latency, and custom screen traces.
  PerformanceService.instance.init();

  // Initialize offline queue engine (loads persisted requests, starts connectivity monitor)
  await OfflineQueue.instance.init();

  // Wire OfflineQueue callbacks — notifies users when queued requests replay.
  // PLATINUM v2: These callbacks were defined but never wired. Users had zero
  // visibility into whether their offline mutations succeeded or silently failed.
  // P1-UXA-004 FIX: Bilingual OfflineQueue snackbar messages.
  // Previous: Hardcoded Arabic strings — unintelligible to English-locale users.
  // Now: Arabic primary + English fallback (matches error widget pattern).
  OfflineQueue.instance.onRequestReplayed = (request) {
    _showSyncSnackBar(
      message: 'تم إرسال طلب مؤجل بنجاح / Queued request sent: ${request.endpoint}',
      isError: false,
    );
  };

  OfflineQueue.instance.onRequestFailed = (request, error) {
    _showSyncSnackBar(
      message: 'فشل طلب مؤجل نهائياً / Queued request failed: ${request.endpoint}',
      isError: true,
    );
  };

  // P0-VE-001 PLATINUM: Initialize deep link service — intercepts
  // email verification and password reset links from the browser.
  // Must init AFTER Firebase but BEFORE runApp so cold-start links
  // are captured even before the navigator is mounted.
  await DeepLinkService.instance.init(navigatorKey);

  // Initialize push notification service (registers background handler, creates channel)
  await PushNotificationService.instance.init();

  // FRIC-2026-F09 FIX: Branded error boundary — replaces Flutter's red error screen.
  // CrashlyticsService captures the real error. This gives users a clean recovery UI
  // instead of a wall of red text. Uses brand colors + Phosphor icons.
  // P1-UXA-005 FIX: Uses platform locale to determine text direction.
  // Previous: Hardcoded TextDirection.rtl — English-locale users saw reversed layout.
  ErrorWidget.builder = (FlutterErrorDetails details) {
    // P1-UXA-005: Determine text direction from platform locale, not hardcoded.
    final platformLocale = WidgetsBinding.instance.platformDispatcher.locale;
    final isRtl = platformLocale.languageCode == 'ar' ||
        platformLocale.languageCode == 'he' ||
        platformLocale.languageCode == 'fa';
    final textDir = isRtl ? TextDirection.rtl : TextDirection.ltr;

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Directionality(
        textDirection: textDir,
        child: Scaffold(
          backgroundColor: const Color(0xFFF4F6F8), // --cloud-white
          body: Center(
            child: Padding(
              padding: const EdgeInsets.all(32),
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Container(
                    width: 80,
                    height: 80,
                    decoration: BoxDecoration(
                      color: const Color(0xFFEF4444).withAlpha(15), // --error-red
                      borderRadius: BorderRadius.circular(20),
                    ),
                    child: Icon(
                      PhosphorIcons.warningOctagon(),
                      size: 40,
                      color: const Color(0xFFEF4444),
                    ),
                  ),
                  const SizedBox(height: 24),
                  // P1-UX-007: Bilingual error message — Arabic primary, English fallback
                  const Text(
                    'حدث خطأ غير متوقع\nAn unexpected error occurred',
                    style: TextStyle(
                      fontSize: 18,
                      fontWeight: FontWeight.w800,
                      color: Color(0xFF0F172A), // --text-heading
                      fontFamily: 'IBM Plex Sans Arabic',
                    ),
                    textAlign: TextAlign.center,
                  ),
                  const SizedBox(height: 8),
                  const Text(
                    'نعتذر عن هذا الخلل. يرجى إعادة تشغيل التطبيق.\nPlease restart the application.',
                    style: TextStyle(
                      fontSize: 14,
                      color: Color(0xFF64748B), // --text-secondary
                      fontFamily: 'IBM Plex Sans Arabic',
                    ),
                    textAlign: TextAlign.center,
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  };

  runApp(const NammerhaMobileApp());
}

/// Shows a non-blocking SnackBar notification for offline queue sync events.
/// Uses the [navigatorKey] to access the current overlay without BuildContext.
void _showSyncSnackBar({required String message, required bool isError}) {
  final context = navigatorKey.currentContext;
  if (context == null) return;

  ScaffoldMessenger.of(context).showSnackBar(
    SnackBar(
      content: Text(
        message,
        style: const TextStyle(
          fontSize: 13,
          fontWeight: FontWeight.w500,
          color: Colors.white,
        ),
      ),
      backgroundColor: isError ? const Color(0xFFB00020) : const Color(0xFF0A6E55),
      behavior: SnackBarBehavior.floating,
      duration: const Duration(seconds: 4),
      margin: const EdgeInsets.all(12),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
    ),
  );
}


class NammerhaMobileApp extends StatelessWidget {
  const NammerhaMobileApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiRepositoryProvider(
      providers: [
        RepositoryProvider<AuthRepository>(
          create: (_) => AuthRepository(),
        ),
        RepositoryProvider<SearchRepository>(
          create: (_) => SearchRepository(),
        ),
      ],
      child: MultiBlocProvider(
        providers: [
          BlocProvider<ThemeCubit>(
            create: (_) => ThemeCubit()..loadSavedTheme(),
          ),
          BlocProvider<AuthBloc>(
            create: (ctx) => AuthBloc(
              authRepository: ctx.read<AuthRepository>(),
            ),
          ),
          BlocProvider<NotificationsBloc>(
            create: (_) => NotificationsBloc(),
          ),
          BlocProvider<LocaleCubit>(
            create: (_) => LocaleCubit()..loadSavedLocale(),
          ),
          BlocProvider<SearchBloc>(
            create: (ctx) => SearchBloc(
              searchRepository: ctx.read<SearchRepository>(),
            ),
          ),
        ],
        child: BlocBuilder<ThemeCubit, ThemeMode>(
          builder: (context, themeMode) {
            return BlocBuilder<LocaleCubit, Locale>(
              builder: (context, activeLocale) {
                return MaterialApp(
                  title: 'نعمّرها',
                  debugShowCheckedModeBanner: false,
                  navigatorKey: navigatorKey,
                  navigatorObservers: [KeyboardDismissObserver()],

                  // Localization — dynamic from LocaleCubit
                  localizationsDelegates: const [
                    GlobalMaterialLocalizations.delegate,
                    GlobalWidgetsLocalizations.delegate,
                    GlobalCupertinoLocalizations.delegate,
                  ],
                  supportedLocales: const [
                    Locale('ar', 'SY'),
                    Locale('ar'),
                    Locale('en'),
                  ],
                  locale: activeLocale,

                  // Theme — controlled by ThemeCubit
                  themeMode: themeMode,
                  theme: NammerhaTheme.light(),
                  darkTheme: NammerhaTheme.dark(),

                  // Entry Point — Navigation Flow Controller
                  home: const _AppFlowController(),

                  // Wave 4: Global ConnectivityBanner — covers ALL screens.
                  // PREVIOUS: Only dashboard had offline indicator.
                  // NOW: Every screen gets automatic offline awareness.
                  // Standard: Syria 2G resilience — user MUST know when offline.
                  builder: (context, child) {
                    return ConnectivityBanner(
                      child: child ?? const SizedBox.shrink(),
                    );
                  },
                );
              },
            );
          },
        ),
      ),
    );
  }
}

/// Controls the app navigation flow:
/// Splash → Onboarding → Auth Check → Login/Dashboard
class _AppFlowController extends StatefulWidget {
  const _AppFlowController();

  @override
  State<_AppFlowController> createState() => _AppFlowControllerState();
}

class _AppFlowControllerState extends State<_AppFlowController> {
  _AppScreen _currentScreen = _AppScreen.splash;

  void _navigateTo(_AppScreen screen) {
    setState(() => _currentScreen = screen);
  }

  /// Wire push notification service to BLoC after authentication.
  void _registerPushNotifications() {
    final pushService = PushNotificationService.instance;

    // Request permission (non-blocking)
    pushService.requestPermission();

    // Register FCM token with backend
    pushService.registerToken();

    // Wire foreground messages to NotificationsBloc
    pushService.onForegroundMessage = (message) {
      if (!mounted) return;
      final notification = message.notification;
      if (notification == null) return;

      // MED-MOB-003: Create typed NotificationModel from FCM payload
      final notifData = NotificationModel.fromJson(<String, dynamic>{
        'notification_id': message.messageId ?? DateTime.now().millisecondsSinceEpoch.toString(),
        'title': notification.title ?? '',
        'body': notification.body ?? '',
        'type': message.data['type'] ?? 'general',
        'is_read': false,
        'created_at': DateTime.now().toIso8601String(),
        'data': message.data,
      });

      context.read<NotificationsBloc>().add(PushNotificationReceived(notifData));
    };

    // Wire notification tap for deep link navigation
    // P0-002 REMEDIATION: Replaced dead `// Future:` comment with live
    // deep link routing. Maps notification types → screen navigation.
    pushService.onNotificationTapped = (data) {
      debugPrint('[Nammerha Push] Deep link: $data');
      _handleDeepLink(data);
    };
  }

  /// Unregister push token on logout.
  void _unregisterPushNotifications() {
    PushNotificationService.instance.unregisterToken();
    PushNotificationService.instance.onForegroundMessage = null;
    PushNotificationService.instance.onNotificationTapped = null;
  }

  /// ═══════════════════════════════════════════════════════════════════════
  /// P0-002 REMEDIATION: Push Notification Deep Link Navigation
  /// ═══════════════════════════════════════════════════════════════════════
  /// Maps notification `type` field to the corresponding screen.
  /// Uses the global [navigatorKey] to navigate without BuildContext.
  ///
  /// Supported types:
  ///   escrow_released   → EscrowSummaryScreen
  ///   proof_verified    → WalletScreen (delivery proofs)
  ///   bid_accepted      → ProjectDetailsScreen
  ///   kyc_verified      → AdminKycScreen (admin) or DashboardScreen
  ///   kyc_rejected      → AdminKycScreen (admin) or DashboardScreen
  ///   order_status      → WalletScreen
  ///   project_funded    → ProjectDetailsScreen
  ///   project_update    → ProjectDetailsScreen
  ///   impact_update     → ImpactInboxScreen
  /// ═══════════════════════════════════════════════════════════════════════
  void _handleDeepLink(Map<String, dynamic> data) {
    final ctx = navigatorKey.currentContext;
    if (ctx == null) return;

    // P1-UXA-006 FIX: Auth guard for deep link navigation.
    // Previous: Navigated directly without checking auth state.
    // A push notification tap after session expiry would crash or show empty screen.
    // Now: Verify user is authenticated before navigating to any protected screen.
    final authState = ctx.read<AuthBloc>().state;
    if (authState is! AuthAuthenticated) {
      debugPrint('[Nammerha Push] Deep link blocked — user not authenticated.');
      return;
    }

    final type = (data['type'] ?? '').toString();
    final projectId = (data['project_id'] ?? data['projectId'] ?? '').toString();

    Widget? targetScreen;

    switch (type) {
      case 'escrow_released':
      case 'escrow_locked':
        targetScreen = const EscrowSummaryScreen();
        break;

      case 'proof_verified':
      case 'proof_submitted':
        // SUSPENDED: DonorProofScreen suspended. Redirect to Wallet.
        targetScreen = const WalletScreen();
        break;

      case 'bid_accepted':
      case 'bid_received':
      case 'project_funded':
      case 'project_update':
      case 'project_published':
        if (projectId.isNotEmpty) {
          targetScreen = ProjectDetailsScreen(projectId: projectId);
        }
        break;

      case 'kyc_verified':
      case 'kyc_rejected':
        targetScreen = const AdminKycScreen();
        break;

      case 'order_status':
      case 'payment_completed':
        targetScreen = const WalletScreen();
        break;

      case 'donation_received':
      case 'donation_refunded':
        // Donation system removed. Redirect to Wallet.
        targetScreen = const WalletScreen();
        break;

      case 'impact_update':
      case 'milestone_reached':
      case 'project_completed':
        targetScreen = const ImpactInboxScreen();
        break;

      case 'admin_escrow_pending':
        targetScreen = const AdminEscrowScreen();
        break;

      default:
        // Unknown type — no navigation, user stays on dashboard
        debugPrint('[Nammerha Push] Unknown deep link type: $type');
        return;
    }

    if (targetScreen != null) {
      Navigator.of(ctx).push(
        MaterialPageRoute(builder: (_) => targetScreen!),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return BlocListener<AuthBloc, AuthState>(
      listener: (context, state) {
        if (state is AuthAuthenticated) {
          _registerPushNotifications();
          _navigateTo(_AppScreen.dashboard);
        } else if (state is AuthUnauthenticated) {
          if (_currentScreen == _AppScreen.dashboard) {
            _unregisterPushNotifications();
            _navigateTo(_AppScreen.login);
          }
        }
      },
      child: AnimatedSwitcher(
        duration: const Duration(milliseconds: 400),
        transitionBuilder: (child, animation) {
          return FadeTransition(
            opacity: animation,
            child: child,
          );
        },
        child: _buildScreen(),
      ),
    );
  }

  Widget _buildScreen() {
    switch (_currentScreen) {
      case _AppScreen.splash:
        return SplashScreen(
          key: const ValueKey('splash'),
          onComplete: () async {
            // Check if user has existing session
            context.read<AuthBloc>().add(AuthCheckSession());
            // P0-006 FIX: Onboarding persistence — skip if already seen.
            final prefs = await SharedPreferences.getInstance();
            final hasSeenOnboarding = prefs.getBool('hasSeenOnboarding') ?? false;
            if (hasSeenOnboarding) {
              _navigateTo(_AppScreen.login);
            } else {
              _navigateTo(_AppScreen.onboarding);
            }

            // P0-VE-001: Process any cold-start deep link after splash.
            // Must happen after navigator is mounted and flow is established.
            WidgetsBinding.instance.addPostFrameCallback((_) {
              DeepLinkService.instance.processPendingDeepLink();
            });
          },
        );
      case _AppScreen.onboarding:
        return BlocBuilder<AuthBloc, AuthState>(
          builder: (context, state) {
            // If already authenticated (from session check), skip to dashboard
            if (state is AuthAuthenticated) {
              // Using post-frame callback to avoid build-during-build
              WidgetsBinding.instance.addPostFrameCallback((_) {
                _navigateTo(_AppScreen.dashboard);
              });
            }
            return OnboardingScreen(
              key: const ValueKey('onboarding'),
              onComplete: () async {
                // P0-006 FIX: Mark onboarding as seen.
                final prefs = await SharedPreferences.getInstance();
                await prefs.setBool('hasSeenOnboarding', true);
                _navigateTo(_AppScreen.login);
              },
            );
          },
        );
      case _AppScreen.login:
        return LoginScreen(
          key: const ValueKey('login'),
          onLoginSuccess: () => _navigateTo(_AppScreen.dashboard),
        );
      case _AppScreen.dashboard:
        return BlocBuilder<AuthBloc, AuthState>(
          builder: (context, state) {
            if (state is AuthAuthenticated) {
              return DashboardScreen(
                // UNIFIED CITIZEN: Include role in key for widget tree rebuild if role changes.
                key: ValueKey('dashboard_${state.user.role}'),
                user: state.user,
                onLogout: () {
                  context.read<AuthBloc>().add(AuthLogoutRequested());
                },
              );
            }
            return const SizedBox.shrink();
          },
        );
    }
  }
}

enum _AppScreen {
  splash,
  onboarding,
  login,
  dashboard,
}

/// UXA-008 FIX: Keyboard Focus Guard
/// Unfocuses the keyboard globally whenever a route (like a BottomSheet) is popped.
/// Prevents UI fracture/jank when the keyboard and sheet animate out simultaneously.
class KeyboardDismissObserver extends NavigatorObserver {
  @override
  void didPop(Route<dynamic> route, Route<dynamic>? previousRoute) {
    FocusManager.instance.primaryFocus?.unfocus();
    super.didPop(route, previousRoute);
  }

  @override
  void didStartUserGesture(Route<dynamic> route, Route<dynamic>? previousRoute) {
    FocusManager.instance.primaryFocus?.unfocus();
    super.didStartUserGesture(route, previousRoute);
  }
}

